/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biornaquantics.labreportloader;

/**
 *
 * @author tihor
 */
public class BQLabReportImporter extends javax.swing.JFrame {

    /**
     * Creates new form BQLabReportImporter
     */
    public BQLabReportImporter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelMain = new javax.swing.JPanel();
        jPanelPDF = new javax.swing.JPanel();
        jToolBarRecordParser = new javax.swing.JToolBar();
        jButtonFirst = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jLabelRecordStatus = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();
        jLabelPDF = new javax.swing.JLabel();
        jPanelData = new javax.swing.JPanel();
        jPanelUserDetails = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonUpload = new javax.swing.JButton();
        jLabelDateCollected = new javax.swing.JLabel();
        jTextFieldDateCollected = new javax.swing.JTextField();
        jScrollPanePDF = new javax.swing.JScrollPane();
        jTablePDF = new javax.swing.JTable();
        jToolBarLoaderButtons = new javax.swing.JToolBar();
        jButtonCMEP = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMain.setLayout(new java.awt.GridLayout(1, 2));

        jPanelPDF.setBorder(javax.swing.BorderFactory.createTitledBorder("PDF"));
        jPanelPDF.setLayout(new java.awt.BorderLayout());

        jToolBarRecordParser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBarRecordParser.setRollover(true);

        jButtonFirst.setText("<<");
        jButtonFirst.setFocusable(false);
        jButtonFirst.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFirst.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarRecordParser.add(jButtonFirst);

        jButtonPrevious.setText("<");
        jButtonPrevious.setFocusable(false);
        jButtonPrevious.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrevious.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarRecordParser.add(jButtonPrevious);

        jLabelRecordStatus.setText("Page 0 of 0  ");
        jToolBarRecordParser.add(jLabelRecordStatus);

        jButtonNext.setText(">");
        jButtonNext.setFocusable(false);
        jButtonNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarRecordParser.add(jButtonNext);

        jButtonLast.setText(">>");
        jButtonLast.setFocusable(false);
        jButtonLast.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLast.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarRecordParser.add(jButtonLast);

        jPanelPDF.add(jToolBarRecordParser, java.awt.BorderLayout.PAGE_START);
        jPanelPDF.add(jLabelPDF, java.awt.BorderLayout.CENTER);

        jPanelMain.add(jPanelPDF);

        jPanelData.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        jPanelData.setLayout(new java.awt.BorderLayout());

        jPanelUserDetails.setLayout(new java.awt.GridLayout(2, 3));

        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelName.setText("Name:");
        jPanelUserDetails.add(jLabelName);
        jPanelUserDetails.add(jTextFieldName);

        jButtonUpload.setText("Upload");
        jPanelUserDetails.add(jButtonUpload);

        jLabelDateCollected.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDateCollected.setText("Date Uploaded:");
        jPanelUserDetails.add(jLabelDateCollected);
        jPanelUserDetails.add(jTextFieldDateCollected);

        jPanelData.add(jPanelUserDetails, java.awt.BorderLayout.PAGE_START);

        jScrollPanePDF.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTablePDF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lab Marker", "Value", "Internal Marker"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPanePDF.setViewportView(jTablePDF);

        jPanelData.add(jScrollPanePDF, java.awt.BorderLayout.CENTER);

        jPanelMain.add(jPanelData);

        getContentPane().add(jPanelMain, java.awt.BorderLayout.CENTER);

        jToolBarLoaderButtons.setRollover(true);

        jButtonCMEP.setText("CMEP");
        jButtonCMEP.setFocusable(false);
        jButtonCMEP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCMEP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarLoaderButtons.add(jButtonCMEP);

        jButton1.setText("IgG4");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarLoaderButtons.add(jButton1);

        getContentPane().add(jToolBarLoaderButtons, java.awt.BorderLayout.PAGE_START);

        jLabelStatus.setText("Status:");
        getContentPane().add(jLabelStatus, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BQLabReportImporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BQLabReportImporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BQLabReportImporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BQLabReportImporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BQLabReportImporter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCMEP;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JLabel jLabelDateCollected;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPDF;
    private javax.swing.JLabel jLabelRecordStatus;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelPDF;
    private javax.swing.JPanel jPanelUserDetails;
    private javax.swing.JScrollPane jScrollPanePDF;
    private javax.swing.JTable jTablePDF;
    private javax.swing.JTextField jTextFieldDateCollected;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JToolBar jToolBarLoaderButtons;
    private javax.swing.JToolBar jToolBarRecordParser;
    // End of variables declaration//GEN-END:variables
}
