/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biornaquantics.labreportloader;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfPage;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.xobject.PdfFormXObject;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;
import org.json.simple.JSONObject;
import org.json.simple.parser.ParseException;

/**
 *
 * @author tihor
 */
public class LabreportImporter extends javax.swing.JFrame {
    int currentPage=0;
    PDDocument document=null;
    PDFRenderer renderer=null;
    private float RENDER_DPI=200;
    /**
     * Creates new form LabreportImporter
     */
    public LabreportImporter() {
        initComponents();
        jLabelCurrentPage.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelControls = new javax.swing.JPanel();
        jButtonCMEP = new javax.swing.JButton();
        jButtonIgG4 = new javax.swing.JButton();
        jLabelFilename = new javax.swing.JLabel();
        jPanelPDFDisplay = new javax.swing.JPanel();
        jLabelPDF = new javax.swing.JLabel();
        jPanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePDFContents = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jFormattedTextFieldMeasuredAt = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanelPDFTraversal = new javax.swing.JPanel();
        jButtonBeginning = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jLabelCurrentPage = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();
        jLabelTotalPages = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCMEP.setText("CMEP");
        jButtonCMEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCMEPActionPerformed(evt);
            }
        });

        jButtonIgG4.setText("IgG4");
        jButtonIgG4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgG4ActionPerformed(evt);
            }
        });

        jLabelFilename.setText(" ");

        javax.swing.GroupLayout jPanelControlsLayout = new javax.swing.GroupLayout(jPanelControls);
        jPanelControls.setLayout(jPanelControlsLayout);
        jPanelControlsLayout.setHorizontalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addComponent(jButtonCMEP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIgG4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelControlsLayout.setVerticalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCMEP)
                    .addComponent(jButtonIgG4)
                    .addComponent(jLabelFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jLabelPDF.setAlignmentY(0.0F);
        jLabelPDF.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelPDFDisplayLayout = new javax.swing.GroupLayout(jPanelPDFDisplay);
        jPanelPDFDisplay.setLayout(jPanelPDFDisplayLayout);
        jPanelPDFDisplayLayout.setHorizontalGroup(
            jPanelPDFDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        jPanelPDFDisplayLayout.setVerticalGroup(
            jPanelPDFDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTablePDFContents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lab Marker", "Value", "Internal Marker"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePDFContents);
        if (jTablePDFContents.getColumnModel().getColumnCount() > 0) {
            jTablePDFContents.getColumnModel().getColumn(1).setResizable(false);
            jTablePDFContents.getColumnModel().getColumn(1).setPreferredWidth(2);
            jTablePDFContents.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setText("Name");

        jFormattedTextFieldMeasuredAt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel2.setText("Date Measured");

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldMeasuredAt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldMeasuredAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 839, Short.MAX_VALUE))
            .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableLayout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jButtonBeginning.setText("<<");
        jButtonBeginning.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonBeginning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBeginningActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("<");
        jButtonPrevious.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jLabelCurrentPage.setText("1");
        jLabelCurrentPage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonNext.setText(">");
        jButtonNext.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonLast.setText(">>");
        jButtonLast.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButtonLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLastActionPerformed(evt);
            }
        });

        jLabelTotalPages.setText("of ");

        javax.swing.GroupLayout jPanelPDFTraversalLayout = new javax.swing.GroupLayout(jPanelPDFTraversal);
        jPanelPDFTraversal.setLayout(jPanelPDFTraversalLayout);
        jPanelPDFTraversalLayout.setHorizontalGroup(
            jPanelPDFTraversalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPDFTraversalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBeginning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCurrentPage, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalPages)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPDFTraversalLayout.setVerticalGroup(
            jPanelPDFTraversalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPDFTraversalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonBeginning)
                .addComponent(jButtonPrevious)
                .addComponent(jLabelCurrentPage)
                .addComponent(jButtonNext)
                .addComponent(jButtonLast)
                .addComponent(jLabelTotalPages))
        );

        jFileMenu.setText("File");
        jMenuBar.add(jFileMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPDFTraversal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPDFDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanelControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPDFTraversal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPDFDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCMEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCMEPActionPerformed
        // TODO add your handling code here:
        try{
            FileFilter pdfFilter = new FileNameExtensionFilter("PDF file", "pdf", "pdf");
            JFileChooser pdfFileChooser=new JFileChooser();
            pdfFileChooser.setCurrentDirectory(new File("D:\\BiornaQuantics\\Complete Metabolic Energy Profile"));
            pdfFileChooser.setFileFilter(pdfFilter);
            int result = pdfFileChooser.showOpenDialog(new JFrame());
            if (result == JFileChooser.APPROVE_OPTION){
                List<JSONObject> pdf_location_mappings = BQJSONParser.parseJSONFile("D:\\BiornaQuantics\\pdf_mapping_CMEP.json");
                Map<String,String> lab_to_internal_mappings=BQJSONParser.parseLabToInternalMappingJSON("D:\\BiornaQuantics\\lab_to_internal_mapping_CMEP.json");
                File selectedFile = pdfFileChooser.getSelectedFile();
                String sFileWithPath=selectedFile.getAbsolutePath();
                jLabelFilename.setText("Parsing "+sFileWithPath);
                Map<String,String> pdfExtract= PDFExtractor.ExtractCMEPPDFData(sFileWithPath,pdf_location_mappings);
                displayPdf(pdfExtract,lab_to_internal_mappings);
                currentPage=1;
                document=PDDocument.load(selectedFile);
                renderer = new PDFRenderer(document);
                renderPage();
            }
        }catch(IOException e){
            String message="Error occured while parsing pdf file.\n"+e.toString();
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",JOptionPane.ERROR_MESSAGE);
        }catch(ParseException e){
            String message="Error occured while parsing pdf file.\n"+e.toString();
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCMEPActionPerformed

    private void jButtonBeginningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBeginningActionPerformed
        // TODO add your handling code here:
        if(document!=null){
            currentPage=1;
            renderPage();
        }
    }//GEN-LAST:event_jButtonBeginningActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
        if(document!=null){
            if(currentPage>1){
                currentPage--;
                renderPage();
            }
        }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        if(document!=null){
            if(currentPage<document.getNumberOfPages()){
                currentPage++;
                renderPage();
            }
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLastActionPerformed
        // TODO add your handling code here:
        if(document!=null){
            currentPage=document.getNumberOfPages();
            renderPage();
        }
    }//GEN-LAST:event_jButtonLastActionPerformed

    private void jButtonIgG4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgG4ActionPerformed
        // TODO add your handling code here:
        try{
            FileFilter pdfFilter = new FileNameExtensionFilter("PDF file", "pdf", "pdf");
            JFileChooser pdfFileChooser=new JFileChooser();
            pdfFileChooser.setCurrentDirectory(new File("D:\\BiornaQuantics\\Food Sensitivities IgG4"));
            pdfFileChooser.setFileFilter(pdfFilter);
            int result = pdfFileChooser.showOpenDialog(new JFrame());
            if (result == JFileChooser.APPROVE_OPTION){
                List<JSONObject> pdf_location_mappings = BQJSONParser.parseJSONFile("D:\\BiornaQuantics\\pdf_mapping_IgG4.json");
                Map<String,String> lab_to_internal_mappings=BQJSONParser.parseLabToInternalMappingJSON("D:\\BiornaQuantics\\lab_to_internal_mapping_IgG4.json");
                File selectedFile = pdfFileChooser.getSelectedFile();
                String sFileWithPath=selectedFile.getAbsolutePath();
                jLabelFilename.setText("Parsing "+sFileWithPath);
                Map<String,String> pdfExtract= PDFExtractor.ExtractIgG4PDFData(sFileWithPath,pdf_location_mappings);
                displayPdf(pdfExtract,lab_to_internal_mappings);
                currentPage=1;
                document=PDDocument.load(selectedFile);
                renderer = new PDFRenderer(document);
                renderPage();
            }
        }catch(IOException e){
            String message="Error occured while parsing pdf file.\n"+e.toString();
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",JOptionPane.ERROR_MESSAGE);
        }catch(ParseException e){
            String message="Error occured while parsing pdf file.\n"+e.toString();
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIgG4ActionPerformed
    
    private void renderPage(){
        try{
            BufferedImage image=renderer.renderImageWithDPI(currentPage-1,RENDER_DPI);
            image=resizeImage(image,jLabelPDF.getHeight(),jLabelPDF.getWidth());
            ImageIcon iconLogo = new ImageIcon(image);
            jLabelPDF.setIcon(iconLogo);
            //jLabelPDF=new javax.swing.JLabel(iconLogo);
            jLabelCurrentPage.setText(""+currentPage);
            jLabelTotalPages.setText("of "+document.getNumberOfPages());
        }catch(IOException e){
            String message="Error occured while parsing pdf file.\n"+e.toString();
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void displayPdf(Map<String,String> pdfExtract,Map<String,String> lab_to_internal_mappings){
        DefaultTableModel tableModel = (DefaultTableModel)jTablePDFContents.getModel();
        tableModel.setRowCount(0);
        int i=0;
        int columns = tableModel.getColumnCount();
        for(String key:pdfExtract.keySet()){
            //System.out.println(key+" "+pdfExtract.get(key));
            String[] splitKeys=key.split("_");
            if(splitKeys[1].equals("Measurement")){
                Object[] row=new Object[columns];
                row[0]=splitKeys[0];
                row[1]=Double.parseDouble(pdfExtract.get(key).replace(" ",""));
                if(lab_to_internal_mappings.containsKey(row[0]))
                    row[2]=lab_to_internal_mappings.get(row[0]).toString();
                else
                    row[2]="";
                tableModel.insertRow(i++, row);
            }
        }
        jTextFieldName.setText(pdfExtract.get("Name_ReportDetails").trim());
        jFormattedTextFieldMeasuredAt.setText(pdfExtract.get("DateOfCollection_ReportDetails"));
    }
    private static BufferedImage resizeImage(BufferedImage img, int height, int width) {
        Image tmp = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        BufferedImage resized = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = resized.createGraphics();
        g2d.drawImage(tmp, 0, 0, null);
        g2d.dispose();
        return resized;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabreportImporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabreportImporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabreportImporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabreportImporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabreportImporter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBeginning;
    private javax.swing.JButton jButtonCMEP;
    private javax.swing.JButton jButtonIgG4;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JFormattedTextField jFormattedTextFieldMeasuredAt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCurrentPage;
    private javax.swing.JLabel jLabelFilename;
    private javax.swing.JLabel jLabelPDF;
    private javax.swing.JLabel jLabelTotalPages;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JPanel jPanelPDFDisplay;
    private javax.swing.JPanel jPanelPDFTraversal;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePDFContents;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
